config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :articles
  resources :items
  resources :entries
  resources :publications
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # root to: 'home#index'
   root to: 'items#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:title, :likes, :resume, :link, :journalist, :publisher, :rating, :user_id)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/1index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Publications</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_publication_path, class: 'btn btn-primary' do %>
    Add New Publication
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            <th>Title</th>
            <th>Likes</th>
            <th>Resume</th>
            <th>Link</th>
            <th>Journalist</th>
            <th>Publisher</th>
            <th>Rating</th>
            <th>User</th>
            
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @publications.each do |publication| %>
        <%= content_tag :tr, id: dom_id(publication), class: dom_class(publication) do %>
          

                      <td><%= publication.title %></td>
                      <td><%= publication.likes %></td>
                      <td><%= publication.resume %></td>
                      <td><%= publication.link %></td>
                      <td><%= publication.journalist %></td>
                      <td><%= publication.publisher %></td>
                      <td><%= publication.rating %></td>
                      <td><%= publication.user %></td>
          
          
            <td><%= link_to 'Show', publication %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/publications/_form.html.erb
<%= form_with(model: publication, local: true) do |form| %>
  <% if publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :likes %>
    <%= form.number_field :likes, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :resume %>
    <%= form.text_area :resume, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :link %>
    <%= form.text_field :link, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :journalist %>
    <%= form.text_field :journalist, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :publisher %>
    <%= form.text_field :publisher, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.number_field :rating, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if publication.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', publication, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if publication.persisted? %>
      <%= link_to "Cancel", publication, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", publications_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Edit Publication</h1>

<%= render 'form', publication: @publication %>

app/views/publications/index.html.erb
<div class="container">
    <div class="row">
		<div class="col-md-12">
		  <h4>Top Ten Horrible Headliners Today</h4>
		  <p>Find the updates on Latest News in this area</p>
		</div>
	</div>

	<div class="row">
        <div class="col-md-3" >
            <div class="row mb-2">
                <div class="col-md-12">
                    <div class="card">
                        <div class="list-group">
                        <a href="#" class="list-group-item list-group-item-action">First item</a>
                        <a href="#" class="list-group-item list-group-item-action">Second item</a>
                        <a href="#" class="list-group-item list-group-item-action">Third item</a>
                    </div> 
                    </div>
                </div>
            </div>
        </div>

		<div class="col-md-6">
		    <div class="row mb-2">
		        <div class="col-md-12">
		            <div class="card bg-warning">
		                <div class="card-body">
		                    <div class="row">
		                        <div class="col-md-4">
		                            <img class="img1" src="http://www.3forty.media/cannix/wp-content/uploads/2018/03/clem-onojeghuo-127166-unsplash-1-500x333.jpg ">
		                        </div>
		                        <div class="col-md-8">
		                            <div class="news-title">
		                                <a href="https://www.nytimes.com/2020/05/22/parenting/drowning-water-safety.html"><h5>Children May Be At Higher Risk of Drowning This Summer ...</h5></a>
		                            </div>
		                            <div class="news-cats">
		                                <ul class="list-unstyled list-inline mb-1">
		                                    <li class="list-inline-item">
		                                            <i class="fa fa-folder-o text-danger"></i>
    		                                        <a href="#"><small>Advertisment</small> </a>
		                                    </li>
		                                     <li class="list-inline-item">
		                                            <i class="fa fa-folder-o text-danger"></i>
    		                                        <a href="#"><small>Author</small> </a>
		                                    </li>
		                                     <li class="list-inline-item">
		                                            <i class="fa fa-folder-o text-danger"></i>
    		                                        <a href="#"><small>4th July 2018</small></a>
		                                    </li>
		                                  
		                                    
		                                    
		                                    
		                                </ul>
		                            </div>
		                            <div class="news-content">
		                                <p>Particular unaffected projection sentiments no my. Music marry as at cause party worth weeks. S... </p>
		                            </div>
		                            <div class="news-buttons">
		                                <button type="button" class="btn btn-outline-danger btn-sm">Read More</button>
		                            </div>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </div>
		    </div>
		    <div class="row mb-2">
		        <div class="col-md-12">
		            <div class="card">
		                <div class="card-body">
		                    <div class="row">
		                        <div class="col-md-4">
		                            <img class="img1" src="http://www.3forty.media/cannix/wp-content/uploads/2018/03/clem-onojeghuo-127166-unsplash-1-500x333.jpg ">
		                        </div>
		                        <div class="col-md-8">
		                            <div class="news-title">
		                                <a href="#"><h5>Uneasy no settle whence nature narrow in afraid</h5></a>
		                            </div>
		                            <div class="news-cats">
		                                <ul class="list-unstyled list-inline mb-1">
		                                    <li class="list-inline-item">
		                                            <i class="fa fa-folder-o text-danger"></i>
    		                                        <a href="#"><small>Advertisment</small> </a>
		                                    </li>
		                                     <li class="list-inline-item">
		                                            <i class="fa fa-folder-o text-danger"></i>
    		                                        <a href="#"><small>Author</small> </a>
		                                    </li>
		                                     <li class="list-inline-item">
		                                            <i class="fa fa-folder-o text-danger"></i>
    		                                        <a href="#"><small>4th July 2018</small></a>
		                                    </li>
		                                  
		                                    
		                                    
		                                    
		                                </ul>
		                            </div>
		                            <div class="news-content">
		                                <p>Particular unaffected projection sentiments no my. Music marry as at cause party worth weeks. S... </p>
		                            </div>
		                            <div class="news-buttons">
		                                <button type="button" class="btn btn-outline-danger btn-sm">Read More</button>
		                            </div>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </div>
		    </div>
		    <div class="row mb-2">
		        <div class="col-md-12">
		            <nav aria-label="Page navigation example">
                      <ul class="pagination">
                        <li class="page-item">
                          <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">«</span>
                            <span class="sr-only">Previous</span>
                          </a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item">
                          <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">»</span>
                            <span class="sr-only">Next</span>
                          </a>
                        </li>
                      </ul>
                    </nav>
		        </div>
		    </div>
		</div>

		<div class="col-md-3">
            <div class="row mb-2">
                <div class="col-md-12">
                    <div class="card">
                        <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                            <div class="card-body">
                                <h5>Categories</h5>
                            </div>
                            </div>
                        </div>
                        </div>
                        <div class="list-group">
                        <a href="#" class="list-group-item list-group-item-action active">First item</a>
                        <a href="#" class="list-group-item list-group-item-action">Second item</a>
                        <a href="#" class="list-group-item list-group-item-action">Third item</a>
                    </div> 
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                    <div class="card-body">
                        <img class="img1" class="" src="http://www.3forty.media/cannix/wp-content/uploads/2018/04/clem-onojeghuo-228522-unsplash-1-768x1153.jpg">
                    </div>
                    </div>
                </div>
            </div>
	    </div>
    </div>
</div>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render 'form', publication: @publication %>

app/views/publications/show.html.erb
<div class="page-header">
  <%= link_to publications_path, class: 'btn btn-default' do %>
    All Publications
  <% end %>
  <%= link_to edit_publication_path(@publication), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show publication</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @publication.title %></dd>

  <dt>Likes:</dt>
  <dd><%= @publication.likes %></dd>

  <dt>Resume:</dt>
  <dd><%= @publication.resume %></dd>

  <dt>Link:</dt>
  <dd><%= @publication.link %></dd>

  <dt>Journalist:</dt>
  <dd><%= @publication.journalist %></dd>

  <dt>Publisher:</dt>
  <dd><%= @publication.publisher %></dd>

  <dt>Rating:</dt>
  <dd><%= @publication.rating %></dd>

  <dt>User:</dt>
  <dd><%= @publication.user %></dd>

</dl>