config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :articles
  resources :items
  resources :entries
  resources :publications
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # root to: 'home#index'
   root to: 'items#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :likes, :resume, :link, :city, :county, :state, :rating, :user_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :likes %>
    <%= form.number_field :likes, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :resume %>
    <%= form.text_area :resume, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :link %>
    <%= form.text_field :link, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :county %>
    <%= form.text_field :county, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :state %>
    <%= form.text_field :state, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.number_field :rating, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if article.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', article, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if article.persisted? %>
      <%= link_to "Cancel", article, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", articles_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form', article: @article %>

app/views/articles/extra.html.erb
<div class="container">
  <div class="row">
		<div class="col-md-9">
		  <h2>Top Ten BS Article Healines of the Day</h2> 
		</div>
	</div>

	<div class="row ">
		<div class="col-md-12">
      <div class="row mb-2">
        <div class="col-md-12">
          <div class="card entry-card">
            <div class="form-group pl-3 pr-3">
              <label for="exampleFormControlSelect1" class="mr5">Select a City</label>
              <select class="form-control" id="exampleFormControlSelect1">
                <option>Los Angeles</option>
                <option>New York</option>
                <option>San Diego</option>
                <option>Seattle</option>
                <option>Atlanta</option>
              </select>
            </div>  
          </div>
        </div>
      </div>
       
        <% if @articles.any? %>
          <% @articles.each do |article| %>
            <div class="row mb-2 ">
              <div class="col-md-12">
                  <div class="card entry-card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="news-title">
                                  <h3> <%= article.title %></h3>
                                </div>
                                <div class="news-cats">
                                    <ul class="list-unstyled list-inline mb-1">
                                        <li class="list-inline-item">
                                                <i class="fa fa-folder-o text-danger"></i>
                                                <a href="#"><small>Advertisment</small> </a>
                                        </li>
                                        <li class="list-inline-item">
                                                <i class="fa fa-folder-o text-danger"></i>
                                                <a href="#"><small>Author</small> </a>
                                        </li>
                                        <li class="list-inline-item">
                                                <i class="fa fa-folder-o text-danger"></i>
                                                <a href="#"><small>4th July 2018</small></a>
                                        </li>   
                                    </ul>
                                </div>
                                <div class="news-content">
                                    <p> <%= truncate(article.resume, :length => 150)  %> </p>
                                </div>
                                <%# points %>
                                <div class="row">
                                  <div class="col-md-12 mb-1">
                                    <div class="card">
                                      <div class="card-body point p-0 m-1">
                                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Enim quae eligendi saepe fugit doloremque 
                                        eum voluptatum magni blanditiis eveniet provident! Qui consequuntur repudiandae assumenda voluptate atque omnis officia quia libero!</p>
                                      </div>
                                    </div> 
                                  </div>
                                  <div class="row">
                                    <div class="col-md-2"></div>
                                    <div class="col-md-10 mb-1">
                                      <div class="card point-reply ">
                                        <div class="card-body pl-1 p-0 point-reply-link">
                                            <%= link_to 'point number un', root_path , class:'point-reply-link', :style => 'color: black' %> 
                                        </div>
                                      </div> 
                                    </div>
                                  </div>
                                  

                                </div>
                            </div>
                        </div>
                    </div>
                  </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <div class="row mb-2 ">
            <div class="col-md-12">
                <div class="card entry-card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="news-title">
                                    <h3></h3>
                                    <h5>Children May Be At Higher Risk of Drowning This Summer ...</h5>
                                </div>
                                <div class="news-cats">
                                    <ul class="list-unstyled list-inline mb-1">
                                        <li class="list-inline-item">
                                                <i class="fa fa-folder-o text-danger"></i>
                                                <a href="#"><small>Advertisment</small> </a>
                                        </li>
                                        <li class="list-inline-item">
                                                <i class="fa fa-folder-o text-danger"></i>
                                                <a href="#"><small>Author</small> </a>
                                        </li>
                                        <li class="list-inline-item">
                                                <i class="fa fa-folder-o text-danger"></i>
                                                <a href="#"><small>4th July 2018</small></a>
                                        </li>   
                                    </ul>
                                </div>
                                <div class="news-content">
                                    <p>Particular unaffected projection sentiments no my. Music marry as at cause party worth weeks. S... </p>
                                </div>
                                <div class="news-buttons">
                                    
                                    <%= link_to 'Read More', root_path , class:'btn btn-outline-secondary btn-sm   feed_link stretched-link' %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          </div>    
        <% end %>

        
    </div>
  </div>

</div>



 

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
		<div class="col-md-9">
		  <h2>Top Ten BS Article Healines of the Day</h2> 
		</div>
	</div>
	<div class="row ">
		<div class="col-md-12">
    <%# search  %>
      <div class="row mb-2">
        <div class="col-md-12">
          <div class="card entry-card">
            <div class="form-group pl-3 pr-3">
              <label for="exampleFormControlSelect1" class="mr5">Select a City</label>
              <select class="form-control" id="exampleFormControlSelect1">
                <option>Los Angeles</option>
                <option>New York</option>
                <option>San Diego</option>
                <option>Seattle</option>
                <option>Atlanta</option>
              </select>
            </div>  
          </div>
        </div>
      </div>
    <%# end search %>
    
        <% if @articles.any? %>
          <% @articles.each do |article| %>
            <div class="row mb-2 ">
              <div class="col-md-12">
                  <div class="card entry-card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="news-title">
                                  <h3> <%= article.title %></h3>
                                </div>
                                <div class="news-cats">
                                    <ul class="list-unstyled list-inline mb-1">
                                        <li class="list-inline-item">
                                                <i class="fa fa-folder-o text-danger"></i>
                                                <a href="#"><small>Advertisment</small> </a>
                                        </li>
                                        <li class="list-inline-item">
                                                <i class="fa fa-folder-o text-danger"></i>
                                                <a href="#"><small>Author</small> </a>
                                        </li>
                                        <li class="list-inline-item">
                                                <i class="fa fa-folder-o text-danger"></i>
                                                <a href="#"><small>4th July 2018</small></a>
                                        </li>   
                                    </ul>
                                </div>
                                <div class='textControl'><%= article.resume %></div>
                                <button class="hide"
                                  data-target="read-more.moreButton"
                                  data-action="read-more#showMore">
                                  Ver más
                                </button>

                                <button class="hide"
                                  data-target="read-more.lessButton"
                                  data-action="read-more#showLess">
                                  Ver menos
                                </button>
                                  <%# <div class="news-content"> %>
                                      <p> <%#= truncate(article.resume, :length => 150)  %> </p>
                                  <%# </div> %>
                                <%# points %>
                                <div class="row">
                                  <div class="col-md-12 mb-1">
                                    <div class="card">
                                      <div class="card-body point p-0 m-1">
                                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Enim quae eligendi saepe fugit doloremque 
                                        eum voluptatum magni blanditiis eveniet provident! Qui consequuntur repudiandae assumenda voluptate atque omnis officia quia libero!</p>
                                      </div>
                                    </div> 
                                  </div>
                                  <div class="row">
                                    <div class="col-md-2"></div>
                                    <div class="col-md-10 mb-1">
                                      <div class="card point-reply ">
                                        <div class="card-body pl-1 p-0 point-reply-link">
                                            <%= link_to 'point number un', root_path , class:'point-reply-link ', :style => 'color: black' %> 
                                        </div>
                                      </div> 
                                    </div>
                                  </div>
                                </div>
                                <div class="news-buttons mt-5">
                                    <%#= link_to 'Read More', article_path(article) , class:'  feed_link stretched-link' %>
                                </div>
                            </div>
                        </div>
                    </div>
                  </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <div>No articles at the moment</div>
        <% end %>

        
    </div>
  </div>

</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class="page-header">
  <%= link_to articles_path, class: 'btn btn-default' do %>
    All Articles
  <% end %>
  <%= link_to edit_article_path(@article), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show article</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @article.title %></dd>

  <dt>Likes:</dt>
  <dd><%= @article.likes %></dd>

  <dt>Resume:</dt>
  <dd><%= @article.resume %></dd>

  <dt>Link:</dt>
  <dd><%= @article.link %></dd>

  <dt>City:</dt>
  <dd><%= @article.city %></dd>

  <dt>County:</dt>
  <dd><%= @article.county %></dd>

  <dt>State:</dt>
  <dd><%= @article.state %></dd>

  <dt>Rating:</dt>
  <dd><%= @article.rating %></dd>

  <dt>User:</dt>
  <dd><%= @article.user %></dd>

</dl>