config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :articles
  resources :items
  resources :entries
  resources :publications
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # root to: 'home#index'
   root to: 'items#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @item.user_id = current_user.id
    # @comment.user = current_user
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    user_id = current_user.id
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :votes, :resume, :link, :region, :rating, :user_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :votes %>
    <%= form.number_field :votes, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :resume %>
    <%= form.text_area :resume, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :link %>
    <%= form.text_field :link, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :region %>
    <%= form.text_field :region, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.number_field :rating, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if item.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', item, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if item.persisted? %>
      <%= link_to "Cancel", item, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", items_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/items/_item.html.erb
<% @publications.each do |publication| %>
    <div class="row mb-2 ">
        <div class="col-md-12">
            <div class="card bg-warning">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="news-title">
                            <h5><%= publication.title %></h5>
                            </div>
                            <div class="news-cats">
                                <ul class="list-unstyled list-inline mb-1">
                                    <li class="list-inline-item">
                                            <i class="fa fa-folder-o text-danger"></i>
                                            <a href="#"><small>Advertisment</small> </a>
                                    </li>
                                        <li class="list-inline-item">
                                            <i class="fa fa-folder-o text-danger"></i>
                                            <a href="#"><small>Author</small> </a>
                                    </li>
                                        <li class="list-inline-item">
                                            <i class="fa fa-folder-o text-danger"></i>
                                            <a href="#"><small>4th July 2018</small></a>
                                    </li>   
                                </ul>
                            </div>
                            <div class="news-content">
                                <p> <%= publication.resume %> </p>
                            </div>
                            <div class="news-buttons">
                                <%= link_to 'Read', root_path , class:'' %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>


<%# create_table "entries", force: :cascade do |t|
    t.string "title"
    t.integer "likes"
    t.text "resume"
    t.string "link"
    t.string "city"
    t.string "county"
    t.string "state"
    t.integer "rating"
    t.bigint "user_id", null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["user_id"], name: "index_entries_on_user_id"
  end %>


    <% @publications.each do |publication| %>
        <%= content_tag :tr, id: dom_id(publication), class: dom_class(publication) do %>
          

                      <td><%= publication.title %></td>
                      <td><%= publication.likes %></td>
                      <td><%= publication.resume %></td>
                      <td><%= publication.link %></td>
                      <td><%= publication.journalist %></td>
                      <td><%= publication.publisher %></td>
                      <td><%= publication.rating %></td>
                      <td><%= publication.user %></td>
          
          
            <td><%= link_to 'Show', publication %></td>
          
        <% end %>
      <% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form', item: @item %>

app/views/items/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <p>Find the updates on Latest News in this area</p>
        </div>

        <div class="col-md-9">
            <% @items.each do |item| %>
                    <div class="row mb-2 ">
                        <div class="col-md-12">
                            <div class="card entry-card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="news-title">
                                                <h3> <%= item.title %></h3>
                                            </div>
                                            <div class="news-cats">
                                                <ul class="list-unstyled list-inline mb-1">
                                                    <li class="list-inline-item">
                                                            <i class="fa fa-folder-o text-danger"></i>
                                                            <a href="#"><small>Advertisment</small> </a>
                                                    </li>
                                                    <li class="list-inline-item">
                                                            <i class="fa fa-folder-o text-danger"></i>
                                                            <a href="#"><small>Author</small> </a>
                                                    </li>
                                                    <li class="list-inline-item">
                                                            <i class="fa fa-folder-o text-danger"></i>
                                                            <a href="#"><small>4th July 2018</small></a>
                                                    </li>   
                                                </ul>
                                            </div>
                                            <div class="news-content">
                                                <p> <%= truncate(item.resume, :length => 150)  %> </p>
                                            </div>
                                            <div class="news-buttons">
                                                <%= link_to 'Read More', item_path(item) , class:'btn btn-outline-secondary btn-sm   feed_link stretched-link' %>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

            <% end %>

        </div>

        <div class="col-md-3">
            <div class="row mb-2">
                <div class="col-md-12">
                    <div class="card entry-card">
                    <h5> <%= link_to 'Submit an Item', new_item_path , class:'' %>  </h5>
                    <%# btn btn-outline-secondary btn-sm   feed_link stretched-link %>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                    <div class="card-body">
                        <img class="img1" class="" src="http://www.3forty.media/cannix/wp-content/uploads/2018/04/clem-onojeghuo-228522-unsplash-1-768x1153.jpg">
                    </div>
                    </div>
                </div>
            </div>
            </div>
        </div>

</div>







 

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form', item: @item %>

app/views/items/show.html.erb
<div class="container">
  <div class="page-header">
    <h3> <%= @item.title %> </h3>
  </div>

  <div><%= @item.resume %></div>
  
<section class="float-right mr-5">
  <ul class="list-inline ">
    <li class="list-inline-item"> 
      California
    </li>
    <li class="list-inline-item">
      3/12/2020
    </li>
    <li class="list-inline-item"> 
      <a href="#" class="btn btn-default btn-sm pull-right pr-2">More ... </a>
    </li>
    <%# <li class="list-group-item">   </li> %>
  </ul>

</section>

 <div class="1link mt-5">
    <%= link_to items_path, class: 'btn btn-default' do %>
        All Items
      <% end %>
      <%= link_to edit_item_path(@item), class: 'btn btn-primary' do %>
        Edit
    <% end %>
 </div>
</div>